client_config_backend: file
client_config:
    client_id: 517811718446-sm1ctcde1c74ao764vjn8sbi4qjl6msr.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive